
import os

ORDER_INVENTORY_TIMEOUT_MS = int(os.getenv("ORDER_INVENTORY_TIMEOUT_MS", "1000"))
ORDER_NOTIFICATION_TIMEOUT_MS = int(os.getenv("ORDER_NOTIFICATION_TIMEOUT_MS", "1000"))
INVENTORY_SERVICE_URL = os.getenv("INVENTORY_SERVICE_URL", "http://inventory_service:8001")
NOTIFICATION_SERVICE_URL = os.getenv("NOTIFICATION_SERVICE_URL", "http://notification_service:8002")
